version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: opali
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: opali
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 123